services:
  master:
    build: .
    container_name: master
    environment:
      - HTTP_PORT=:8081
      - GRPC_PORT=:50001
      - IS_MASTER=1
    ports:
      - "8081:8081"
      - "50001:50001"

  replica1:
    build: .
    container_name: replica1
    environment:
      - HTTP_PORT=:8082
      - GRPC_PORT=:50002
    ports:
      - "8082:8082"
      - "50002:50002"

  replica2:
    build: .
    container_name: replica2
    environment:
      - HTTP_PORT=:8083
      - GRPC_PORT=:50003
    ports:
      - "8083:8083"
      - "50003:50003"

